import { useState } from "react";
import { useNWSPoints, useNWSDiscussion } from "../hooks/useWeatherQuery";
import { useDailyBrief } from "../hooks/useDailyBrief";
import type { Location } from "../hooks/useLocation";
import { CardSkeleton } from "../components/WeatherSkeleton";
import { MessageSquare, Sparkles } from "lucide-react";
import { format, parseISO } from "date-fns";

interface Props { location: Location }

export default function ForecastDiscussion({ location }: Props) {
  const { data: nwsPoints } = useNWSPoints(location);
  const office = nwsPoints?.properties?.cwa;
  const { data: discussion, isLoading } = useNWSDiscussion(office);
  const { data: brief, isLoading: briefLoading } = useDailyBrief();
  const [tab, setTab] = useState<"raw" | "friendly">("raw");

  const plain = brief?.content.discussion_plain?.trim();

  return (
    <div className="p-4 md:p-6 space-y-5">
      <div className="flex items-center gap-2">
        <MessageSquare className="w-5 h-5 text-primary" />
        <h2 className="text-xl font-bold">Forecast Discussion</h2>
      </div>
      <p className="text-sm text-muted-foreground">{location.name} · NWS Office: {office ?? "loading…"}</p>

      {isLoading && <CardSkeleton rows={8} />}

      {!isLoading && !discussion && (
        <div className="bg-card border border-border rounded-xl p-6 text-center text-muted-foreground text-sm">
          No forecast discussion available for {office ?? "this location"}.
        </div>
      )}

      {!isLoading && discussion && (
        <>
          <div className="flex gap-2">
            <button
              onClick={() => setTab("raw")}
              className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-colors ${tab === "raw" ? "bg-primary text-primary-foreground" : "bg-card border border-border hover:border-primary/40"}`}
            >
              Technical · Local
            </button>
            <button
              onClick={() => setTab("friendly")}
              className={`px-4 py-1.5 rounded-lg text-sm font-medium transition-colors ${tab === "friendly" ? "bg-primary text-primary-foreground" : "bg-card border border-border hover:border-primary/40"}`}
            >
              Plain Language
            </button>
          </div>

          {tab === "raw" && discussion.issuanceTime && (
            <div className="text-xs text-muted-foreground">
              Issued: {(() => { try { return format(parseISO(discussion.issuanceTime), "MMM d, yyyy h:mm a"); } catch { return discussion.issuanceTime; } })()}
            </div>
          )}

          {tab === "raw" && (
            <div className="bg-card border border-border rounded-xl p-4">
              <pre className="text-xs leading-relaxed whitespace-pre-wrap font-mono text-muted-foreground overflow-x-auto">
                {discussion.productText}
              </pre>
            </div>
          )}

          {/* Plain-language tab: the nightly SSWX Storm Engine national discussion
              (one shared AI artifact — no per-request call). */}
          {tab === "friendly" && (
            <>
              {briefLoading && <CardSkeleton rows={5} />}

              {!briefLoading && plain && (
                <div className="bg-card border border-border rounded-xl p-4">
                  <div className="flex items-center gap-2 mb-3">
                    <Sparkles className="w-4 h-4 text-primary" />
                    <h3 className="text-sm font-semibold text-primary">SSWX Plain-Language Discussion</h3>
                    {brief?.generatedAt && (
                      <span className="text-[10px] text-muted-foreground ml-auto">
                        {(() => { try { return format(parseISO(brief.generatedAt!), "MMM d · h:mm a"); } catch { return ""; } })()}
                      </span>
                    )}
                  </div>
                  <div className="text-sm leading-relaxed whitespace-pre-wrap">{plain}</div>
                  <div className="mt-4 text-xs text-muted-foreground">
                    SSWX nightly national discussion · Generated by AI · Not official NWS guidance · For your local technical detail, see the Technical tab.
                  </div>
                </div>
              )}

              {!briefLoading && !plain && (
                <div className="bg-card border border-border rounded-xl p-6 text-center">
                  <Sparkles className="w-8 h-8 mx-auto mb-3 text-primary opacity-50" />
                  <p className="text-sm text-muted-foreground">
                    The plain-language discussion is written by the nightly SSWX Storm Engine and refreshes each morning. Check back shortly — today's edition isn't ready yet.
                  </p>
                </div>
              )}
            </>
          )}
        </>
      )}
    </div>
  );
}
