-- The badge catalogue: forty-two new achievements and thirteen region nicknames.
--
-- Seeded rather than created by hand so that the definition and the rule that
-- awards it arrive together and cannot drift. Everything is idempotent: running
-- this twice changes nothing, and editing a label here updates it in place
-- without disturbing anybody who has already earned the badge.
--
-- The region badges are not earned by doing anything. They are a nickname for
-- where a member watches the sky from, taken from the first location they ever
-- saved, and they sit on top of the achievements rather than counting toward
-- them.

insert into public.badge_defs (id, label, color, description, badge_group) values
  ('five-thousand', 'Five Thousand', '#f59e0b', 'Five thousand points on the board.', 'Achievement'),
  ('ten-thousand', 'Ten Thousand', '#f97316', 'Ten thousand points. That is a lot of correct guesses.', 'Achievement'),
  ('high-scorer', 'High Scorer', '#fb7185', 'Twenty-five thousand points, all time.', 'Achievement'),
  ('big-day', 'Big Day', '#fbbf24', 'Five hundred points in a single day.', 'Achievement'),
  ('perfect-storm', 'Perfect Storm', '#f43f5e', 'A thousand points in a single day.', 'Achievement'),
  ('trivia-hundred', 'Trivia Century', '#22d3ee', 'A hundred trivia questions answered correctly.', 'Achievement'),
  ('trivia-scholar', 'Scholar', '#38bdf8', 'Two hundred and fifty correct answers. You know things.', 'Achievement'),
  ('trivia-regular', 'Regular', '#7dd3fc', 'Twenty-five trivia questions attempted.', 'Achievement'),
  ('trivia-devoted', 'Devoted', '#60a5fa', 'A hundred trivia questions attempted, right or wrong.', 'Achievement'),
  ('first-forecast', 'First Forecast', '#a3e635', 'You locked in your first forecast-game pick.', 'Achievement'),
  ('ten-forecasts', 'Ten Rounds', '#84cc16', 'Ten rounds of the forecast game played.', 'Achievement'),
  ('fifty-forecasts', 'Fifty Rounds', '#65a30d', 'Fifty rounds played. You show up.', 'Achievement'),
  ('hundred-forecasts', 'Hundred Rounds', '#4d7c0f', 'A hundred rounds of the forecast game.', 'Achievement'),
  ('triple-crown', 'Triple Crown', '#eab308', 'Three forecast-game wins.', 'Achievement'),
  ('dynasty', 'Dynasty', '#ca8a04', 'Ten forecast-game wins.', 'Achievement'),
  ('first-month', 'First Month', '#94a3b8', 'Thirty days with StormSync.', 'Achievement'),
  ('half-year', 'Half a Year', '#a1a1aa', 'A hundred and eighty days with us.', 'Achievement'),
  ('two-years', 'Two Years', '#e2e8f0', 'Two years with StormSync. Thank you.', 'Achievement'),
  ('recruiter-three', 'Recruiter', '#c084fc', 'Three people joined because of you.', 'Achievement'),
  ('recruiter-ten', 'Ambassador', '#a855f7', 'Ten referrals. You are why this thing grows.', 'Achievement'),
  ('recruiter-25', 'Kingmaker', '#9333ea', 'Twenty-five referrals.', 'Achievement'),
  ('starter-kit', 'Starter Kit', '#67e8f9', 'Five modules unlocked.', 'Achievement'),
  ('well-equipped', 'Well Equipped', '#22d3ee', 'Fifteen modules unlocked.', 'Achievement'),
  ('the-lot', 'The Lot', '#06b6d4', 'Every module StormSync has.', 'Achievement'),
  ('curious', 'Curious', '#fda4af', 'Opened five different modules.', 'Achievement'),
  ('explorer', 'Explorer', '#fb7185', 'Opened fifteen different modules.', 'Achievement'),
  ('cartographer', 'Cartographer', '#e11d48', 'Opened thirty different modules. You have been everywhere.', 'Achievement'),
  ('week-one', 'Week One', '#5eead4', 'Seven days where you actually opened the app.', 'Achievement'),
  ('thirty-days', 'Thirty Days In', '#2dd4bf', 'Thirty separate days of using StormSync.', 'Achievement'),
  ('hundred-days', 'Hundred Days', '#14b8a6', 'A hundred days of showing up.', 'Achievement'),
  ('push-on', 'Buzzed', '#89cff0', 'Push alerts, unlocked.', 'Achievement'),
  ('reachable', 'Reachable', '#d9b775', 'Contact alerts — we can reach a person, not just a device.', 'Achievement'),
  ('day-ahead', 'Day Ahead', '#ff8a3d', 'Outlook & Vault. You know about the day before it starts.', 'Achievement'),
  ('direct-line', 'Direct Line', '#ff4d55', 'The top of the alert ladder. We come to you.', 'Achievement'),
  ('three-places', 'Three Places', '#bef264', 'Three saved locations.', 'Achievement'),
  ('watchlist', 'Watchlist', '#a3e635', 'Ten saved locations. Somebody has family everywhere.', 'Achievement'),
  ('collector', 'Collector', '#fcd34d', 'Ten badges earned.', 'Achievement'),
  ('completionist', 'Completionist', '#f59e0b', 'Twenty-five badges. At this point you are showing off.', 'Achievement'),
  ('first-warning', 'First Warning', '#f87171', 'Your first severe-weather warning through StormSync.', 'Achievement'),
  ('ten-warnings', 'Weathered', '#ef4444', 'Ten warnings for your locations.', 'Achievement'),
  ('fifty-warnings', 'Storm-Tested', '#dc2626', 'Fifty warnings. You live somewhere interesting.', 'Achievement'),
  ('supporter', 'Supporter', '#22d3ee', 'On a paid plan.', 'Tier'),
  ('region-lake-effect', 'Lake Effect', '#38bdf8', 'Watches the sky from the Great Lakes.', 'Role'),
  ('region-heartland', 'Heartland', '#f59e0b', 'Watches the sky from the Upper Midwest.', 'Role'),
  ('region-alley', 'Alley Cat', '#ef4444', 'Watches the sky from Tornado Alley.', 'Role'),
  ('region-dixie', 'Dixie Alley', '#f97316', 'Watches the sky from the Deep South.', 'Role'),
  ('region-gulf', 'Gulf Coaster', '#2dd4bf', 'Watches the sky from the Gulf and the Southeast.', 'Role'),
  ('region-noreaster', 'Nor''easter', '#818cf8', 'Watches the sky from the Northeast.', 'Role'),
  ('region-blue-ridge', 'Blue Ridge', '#4ade80', 'Watches the sky from the Mid-Atlantic and the Appalachians.', 'Role'),
  ('region-high-country', 'High Country', '#c084fc', 'Watches the sky from the Rockies.', 'Role'),
  ('region-dryline', 'Dryline', '#fbbf24', 'Watches the sky from the desert Southwest.', 'Role'),
  ('region-pineapple', 'Pineapple Express', '#34d399', 'Watches the sky from the Pacific Northwest.', 'Role'),
  ('region-golden', 'Golden State', '#facc15', 'Watches the sky from California.', 'Role'),
  ('region-frontier', 'Last Frontier', '#93c5fd', 'Watches the sky from Alaska.', 'Role'),
  ('region-island', 'Island Watch', '#f472b6', 'Watches the sky from Hawaii.', 'Role')
on conflict (id) do update set
  label = excluded.label,
  color = excluded.color,
  description = excluded.description,
  badge_group = excluded.badge_group;

insert into public.badge_rules (badge_id, kind, threshold, param) values
  ('five-thousand', 'points_total', 5000, null),
  ('ten-thousand', 'points_total', 10000, null),
  ('high-scorer', 'points_total', 25000, null),
  ('big-day', 'points_day_best', 500, null),
  ('perfect-storm', 'points_day_best', 1000, null),
  ('trivia-hundred', 'trivia_correct', 100, null),
  ('trivia-scholar', 'trivia_correct', 250, null),
  ('trivia-regular', 'trivia_answered', 25, null),
  ('trivia-devoted', 'trivia_answered', 100, null),
  ('first-forecast', 'game_plays', 1, null),
  ('ten-forecasts', 'game_plays', 10, null),
  ('fifty-forecasts', 'game_plays', 50, null),
  ('hundred-forecasts', 'game_plays', 100, null),
  ('triple-crown', 'game_wins', 3, null),
  ('dynasty', 'game_wins', 10, null),
  ('first-month', 'days_member', 30, null),
  ('half-year', 'days_member', 180, null),
  ('two-years', 'days_member', 730, null),
  ('recruiter-three', 'referrals', 3, null),
  ('recruiter-ten', 'referrals', 10, null),
  ('recruiter-25', 'referrals', 25, null),
  ('starter-kit', 'modules_owned', 5, null),
  ('well-equipped', 'modules_owned', 15, null),
  ('the-lot', 'modules_owned', 37, null),
  ('curious', 'modules_explored', 5, null),
  ('explorer', 'modules_explored', 15, null),
  ('cartographer', 'modules_explored', 30, null),
  ('week-one', 'active_days', 7, null),
  ('thirty-days', 'active_days', 30, null),
  ('hundred-days', 'active_days', 100, null),
  ('push-on', 'alert_level', 2, null),
  ('reachable', 'alert_level', 3, null),
  ('day-ahead', 'alert_level', 4, null),
  ('direct-line', 'alert_level', 5, null),
  ('three-places', 'locations_saved', 3, null),
  ('watchlist', 'locations_saved', 10, null),
  ('collector', 'badges_earned', 10, null),
  ('completionist', 'badges_earned', 25, null),
  ('first-warning', 'warnings_received', 1, null),
  ('ten-warnings', 'warnings_received', 10, null),
  ('fifty-warnings', 'warnings_received', 50, null),
  ('supporter', 'tier_at_least', 2, null),
  ('region-lake-effect', 'region', 1, 'lake-effect'),
  ('region-heartland', 'region', 1, 'heartland'),
  ('region-alley', 'region', 1, 'alley'),
  ('region-dixie', 'region', 1, 'dixie'),
  ('region-gulf', 'region', 1, 'gulf'),
  ('region-noreaster', 'region', 1, 'noreaster'),
  ('region-blue-ridge', 'region', 1, 'blue-ridge'),
  ('region-high-country', 'region', 1, 'high-country'),
  ('region-dryline', 'region', 1, 'dryline'),
  ('region-pineapple', 'region', 1, 'pineapple'),
  ('region-golden', 'region', 1, 'golden'),
  ('region-frontier', 'region', 1, 'frontier'),
  ('region-island', 'region', 1, 'island')
on conflict (badge_id) do update set
  kind = excluded.kind,
  threshold = excluded.threshold,
  param = excluded.param,
  updated_at = now();
