-- storm_engine_runs.id had no way to fill itself in.
--
-- The column is a plain `bigint not null` with no default and no identity, so
-- every insert the Storm Engine attempted was rejected for a null id. The
-- engine's own logging is best-effort and swallows the failure, so the symptom
-- was silence: the run log simply stopped on 2026-09-01 while the engine kept
-- running perfectly every morning — the daily brief has an unbroken row for
-- every day since. Anyone reading the admin health view would have concluded
-- the engine was dead.
--
-- Restored as an identity column rather than a serial: same behaviour, but the
-- sequence is owned by the column, so it cannot be separated from it again by a
-- grant replay or a restore.
alter table public.storm_engine_runs
  alter column id add generated by default as identity (start with 1000);
