-- Six FAQ entries for everything that shipped without one.
--
-- Badges, raffles, what Advanced actually means, why a phone might not be
-- getting notifications, what happens when the signal drops, and where last
-- month's champion went. All of it exists in the app; none of it was written
-- down anywhere a member would look.
--
-- Re-runnable: the six slots are cleared first, so applying this twice leaves
-- six entries rather than twelve.
delete from public.faq_entries
 where category_id = '1b25cb58-d5d2-4e0b-be8b-64f07c4ecbd0'
   and sort_order between 12 and 17;

insert into public.faq_entries (kind, sort_order, title, sections, category_id) values
  ('general', 12, 'What are badges, and how do I earn them?', '[{"heading": "They earn themselves", "body": "There are 128 badges that award themselves the moment you qualify \u2014 no claiming, no asking. They cover how long you have been here, how often you turn up, streaks of consecutive days, how much of the app you have explored, the games and the trivia, points, alerts delivered, referrals, and saved locations. You get a notification when one lands."}, {"heading": "Where you watch from", "body": "Your first saved location earns a region badge automatically. It is set once, from where you started, and it does not follow you around."}, {"heading": "Bringing people in", "body": "Referrals have their own ladder, and there is a second set for referrals that actually became paying members."}, {"heading": "What they look like", "body": "Each badge is a struck medallion in its own colour with its own icon. How ornate the rim is tells you how hard it was: common, rare, epic, then legendary, which carries a second ring and a light that keeps turning. They are on your profile."}, {"heading": "The handmade ones", "body": "A few badges have no rule behind them at all. Those are given by hand, and they are the rarest things in the case."}]'::jsonb, '1b25cb58-d5d2-4e0b-be8b-64f07c4ecbd0'),
  ('general', 13, 'How do the raffles work?', '[{"heading": "Four draws", "body": "Monthly and yearly run on their period. Random can be run at any time. Blessed is not earned at all \u2014 it is given."}, {"heading": "What your plan includes", "body": "Basic: one monthly entry. VIP: one monthly and one yearly. Advanced: two of each. They appear on their own at the start of each period, and if you upgrade mid-month yours arrive within a day."}, {"heading": "More than one way in", "body": "Tickets are also handed out for taking part. Monthly and yearly entries reset with their period; random and blessed tickets build up until they win something, and are spent when they do."}, {"heading": "How the winner is picked", "body": "Weighted by tickets \u2014 every ticket is a separate entry, so holding four genuinely is four chances rather than one. The draw is recorded with how many entrants there were and how many tickets were in the pool."}, {"heading": "Getting the prize", "body": "Most prizes land on your account in the same moment you win: a discount code in your name, points on the leaderboard, a module added to your plan, an alert level unlocked. The few that need a person \u2014 a chase seat, months added to a subscription \u2014 say so."}, {"heading": "Where to look", "body": "My Profile shows the tickets you hold in each draw and who won recently."}]'::jsonb, '1b25cb58-d5d2-4e0b-be8b-64f07c4ecbd0'),
  ('general', 14, 'What does the Advanced plan actually include?', '[{"heading": "Every module", "body": "All of them. Not a long list that happens to be most of them \u2014 the rule is the tier, so anything added to the app afterwards is yours the moment it appears. You never have to ask for it and nothing has to be re-issued."}, {"heading": "Everything else", "body": "All five alert levels, two monthly raffle entries and two yearly ones."}]'::jsonb, '1b25cb58-d5d2-4e0b-be8b-64f07c4ecbd0'),
  ('general', 15, 'My phone is not getting notifications', '[{"heading": "Check the device is registered", "body": "A push goes to a device, not to an account, and a registration made in a browser you have since cleared or replaced will look fine from our side while reaching nothing. My Profile lists the devices registered to you, when each was added, and when each last confirmed it received something."}, {"heading": "Register the one in your hand", "body": "If the phone you are holding is not in that list, there is a button to add it. You will be asked for notification permission once."}, {"heading": "Prove it", "body": "Send a test. It waits for the device itself to confirm delivery rather than trusting that the push was accepted \u2014 accepted and delivered are not the same thing, and a dead registration accepts everything."}]'::jsonb, '1b25cb58-d5d2-4e0b-be8b-64f07c4ecbd0'),
  ('general', 16, 'What happens when I lose signal?', '[{"heading": "You get told", "body": "A strip appears across the top saying you are offline and that what you are looking at is the last data that arrived. Without it, a dropped connection looks exactly like calm weather."}, {"heading": "It comes back on its own", "body": "When the network returns, whatever is on screen refreshes itself and the strip says so briefly before getting out of the way."}, {"heading": "Pull to refresh", "body": "Anywhere in the app, pull down from the top and the page reloads its data \u2014 the radar reloads the radar, the dashboard reloads the dashboard."}, {"heading": "Install it", "body": "Installed to your home screen, the app keeps its shell cached and opens instantly even on a bad connection. My Profile has the button."}]'::jsonb, '1b25cb58-d5d2-4e0b-be8b-64f07c4ecbd0'),
  ('general', 17, 'Who won the leaderboard last month?', '[{"heading": "It is recorded now", "body": "A month or a year seals its champion the day after it ends, from the standings as they stood. The Leaderboard shows past champions underneath the current board."}, {"heading": "Points come from two places", "body": "The Forecast Game and the Daily Trivia are totalled together into one standing \u2014 there is no separate board to chase."}]'::jsonb, '1b25cb58-d5d2-4e0b-be8b-64f07c4ecbd0');
-- 6 entries
